### PR TITLE
Restore history

### PR DESCRIPTION
**Pull request by KuleRucket**
A few days ago the history got removed from daily_count.csv. Since then it continues to get added so this puts the history back again.

### CODE REVIEW

**Comment by KuleRucket** [comment]
The history disappeared again. Never mind, I'll use a fork. It is immediately noticeable to be because I import the file into Google sheet for further analysis using a direct link and everything changes to #N/A in my filters.

**Comment by scarnecchia** [comment]
@KuleRucket : I'm not sure what I'm seeing what you're seeing. The history is intact for me.

**Comment by KuleRucket** [comment]
Only for the first part of the file. Filter e.g. on Russia + Tanks and there are only entries for the past 4 updates.

**Comment by scarnecchia** [comment]
@KuleRucket: Thanks, I'm traveling for the weekend but I'll investigate this further on Monday and see if I can't figure it out.

**Pull request merged**
